name: goreleaser

on:
  create:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14.2"
      - name: Test
        run: go test ./...
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
      -
        name: Publish on Bintray
        run: ./.bintray
        env:
          API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  publishOpenWRT:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout OpenWRT
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.RELEASE_GH_TOKEN }}
          repository: openwrt/packages
      -
        name: Update latest version
        run: |
          #TODO: use 'sed' to update 'net/nextdns/Makefile'        
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.RELEASE_GH_TOKEN }}
          commit-message: 'nextdns: Update to version ${{ TODO: set version number without v }}'
          title: 'nextdns: Update to version ${{ TODO: set version number without v }}'
          branch: 'rs-nextdns-${{ TODO: set version number without v }}'
