name: Release

on:
  create:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14.2"
      - name: Test
        run: go test ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
      - name: Publish on Bintray
        run: ./.bintray
        env:
          API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  OpenWRTVariables:
    runs-on: ubuntu-latest
    outputs:
      OPENWRT_HASH: ${{ steps.output.outputs.OPENWRT_HASH }}
      VERSION: ${{ steps.output.outputs.VERSION }}
      AUTHOR_NAME: ${{ steps.output.outputs.AUTHOR_NAME }}
      AUTHOR_EMAIL: ${{ steps.output.outputs.AUTHOR_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compute OpenWRT variables
        id: output
        run: |
          export TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          export VERSION=${TAG:1}
          export MTIME=$(git log -1 --format='@%ct')
          export AUTHOR_NAME=$(git log -1 --format=%aN)
          export AUTHOR_EMAIL=$(git log -1 --format=%aE)
          umask 022
          curl -Ls https://api.github.com/repos/mad-it/nextdns/tarball/$TAG | tar -xz --no-same-permissions -C /tmp
          mv /tmp/*nextdns* /tmp/nextdns-$VERSION
          XZ_OPT=-7e tar --numeric-owner --owner=0 --group=0 --sort=name --mtime=$MTIME -J -C /tmp  -cf /tmp/nextdns-$VERSION.tar.xz nextdns-$VERSION 
          export OPENWRT_HASH=$(sha256sum /tmp/nextdns-$VERSION.tar.xz | awk '{print $1}')

          echo "::set-output name=OPENWRT_HASH::$OPENWRT_HASH"
          echo "::set-output name=VERSION::$VERSION"
          echo "::set-output name=AUTHOR_NAME::$AUTHOR_NAME"
          echo "::set-output name=AUTHOR_EMAIL::$AUTHOR_EMAIL"
  publishToOpenWRT-master:
    runs-on: ubuntu-latest
    needs: OpenWRTVariables
    outputs:
      OPENWRT_MASTER_PR_NUMBER: ${{ steps.cpr.outputs.pr_number }}
    steps:
      - name: Checkout OpenWRT packages repository fork
        uses: actions/checkout@v2
        with:
          repository: mad-it/packages
          ref: master
      - name: Rebase fork
        run: |
          git remote add upstream https://github.com/openwrt/packages.git
          git fetch upstream
          git reset --hard upstream/master
      - name: Update nextdns Makefile
        run: |
          sed -i 's/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.OpenWRTVariables.outputs.VERSION }}/' net/nextdns/Makefile
          sed -i 's/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.OpenWRTVariables.outputs.OPENWRT_HASH }}/' net/nextdns/Makefile
      - name: Create pull request towards OpenWRT
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.RELEASE_GH_TOKEN }}
          commit-message: |
            nextdns: Update to version ${{ needs.OpenWRTVariables.outputs.VERSION }}

            Signed-off-by: ${{ needs.OpenWRTVariables.outputs.AUTHOR_NAME }} <${{ needs.OpenWRTVariables.outputs.AUTHOR_EMAIL }}>
          title: "nextdns: Update to version ${{ needs.OpenWRTVariables.outputs.VERSION }}"
          branch: nextdns-${{ needs.OpenWRTVariables.outputs.VERSION }}-master
          body: Update to version ${{ needs.OpenWRTVariables.outputs.VERSION }}
          base: master
          author: ${{ needs.OpenWRTVariables.outputs.AUTHOR_NAME }} <${{ needs.OpenWRTVariables.outputs.AUTHOR_EMAIL }}>
          # request-to-parent: true
  publishToOpenWRT-backports:
    runs-on: ubuntu-latest
    needs: [OpenWRTVariables, publishToOpenWRT-master]
    strategy:
      matrix:
        openwrt-branch: ["openwrt-19.07"]
    steps:
      - name: Checkout OpenWRT packages repository fork
        uses: actions/checkout@v2
        with:
          repository: mad-it/packages
          ref: ${{ matrix.openwrt-branch }}
      - name: Rebase fork
        run: |
          git remote add upstream https://github.com/openwrt/packages.git
          git fetch upstream
          git reset --hard upstream/${{ matrix.openwrt-branch }}
      - name: Update nextdns Makefile
        run: |
          sed -i 's/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.OpenWRTVariables.outputs.VERSION }}/' net/nextdns/Makefile
          sed -i 's/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.OpenWRTVariables.outputs.OPENWRT_HASH }}/' net/nextdns/Makefile
      - name: Create pull request towards OpenWRT
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.RELEASE_GH_TOKEN }}
          commit-message: |
            nextdns: Update to version ${{ needs.OpenWRTVariables.outputs.VERSION }}

            Signed-off-by: ${{ needs.OpenWRTVariables.outputs.AUTHOR_NAME }} <${{ needs.OpenWRTVariables.outputs.AUTHOR_EMAIL }}>
          title: "nextdns: Update to version ${{ needs.OpenWRTVariables.outputs.VERSION }}"
          branch: nextdns-${{ needs.OpenWRTVariables.outputs.VERSION }}-${{ matrix.openwrt-branch }}
          body: |
            Update to version ${{ needs.OpenWRTVariables.outputs.VERSION }}

            PR towards master has been created #${{ needs.publishToOpenWRT-master.outputs.OPENWRT_MASTER_PR_NUMBER }}
          base: ${{ matrix.openwrt-branch }}
          author: ${{ needs.OpenWRTVariables.outputs.AUTHOR_NAME }} <${{ needs.OpenWRTVariables.outputs.AUTHOR_EMAIL }}>
          # request-to-parent: true
